apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cortex-staging-auto
  region: us-east-1
  version: '1.34'
  tags:
    karpenter.sh/discovery: cortex-staging-auto
vpc:
  id: vpc-001c8a06e58704b50
  subnets:
    public:
      us-east-1a:
        id: subnet-09eef5663c8e7e9b2
      us-east-1b:
        id: subnet-0416ece4feb5f3586
      us-east-1c:
        id: subnet-08aa0910b39c51132
      us-east-1d:
        id: subnet-0e57d0a746628567e
      us-east-1f:
        id: subnet-07d789d81b989fa17
iam:
  withOIDC: true
  podIdentityAssociations:
  - namespace: karpenter
    serviceAccountName: karpenter
    roleName: cortex-staging-auto-karpenter
    permissionPolicyARNs:
    - arn:aws:iam::746038690600:policy/KarpenterControllerPolicy-cortex-staging-auto
iamIdentityMappings:
- arn: arn:aws:iam::746038690600:role/KarpenterNodeRole-cortex-staging-auto
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes
addons:
- name: vpc-cni
- name: coredns
- name: kube-proxy
- name: eks-pod-identity-agent
- name: aws-ebs-csi-driver
  wellKnownPolicies:
    ebsCSIController: true
managedNodeGroups:
- name: system-nodes
  instanceType: t3.medium
  amiFamily: AmazonLinux2023
  minSize: 2
  maxSize: 3
  privateNetworking: false
