apiVersion: v1
kind: Service
metadata:
  name: cortex-app
  namespace: cortex-app
  labels:
    app.kubernetes.io/name: cortex-app
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cortex-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cortex-app
  namespace: cortex-app
  labels:
    app.kubernetes.io/name: cortex-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746038690600:role/cortex-app-sa-role

