apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: clickhouse-pool
spec:
  template:
    metadata:
      labels:
        role: clickhouse
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["c7i.large", "c7i.xlarge", "c6i.large", "c6i.xlarge"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d", "us-east-1f"]
      taints:
        - key: workload
          value: clickhouse
          effect: NoSchedule
  limits:
    cpu: 100
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30m
    # Prevent disruption of nodes with database pods
    budgets:
      - nodes: "0"
        reasons:
          - Drifted
          - Underutilized