import base64
from dataclasses import dataclass
from typing import Dict

import requests

from api.models import CustomerConfigResolved
from api.settings import settings


@dataclass
class GitFile:
    path: str
    content: str


class GitOpsWriter:
    def __init__(self, config: CustomerConfigResolved, outputs: Dict):
        self.config = config
        self.outputs = outputs or {}
        self.customer_id = config.customer_id
        self.domain = config.domain
        self.branch = self._resolve_branch()

    def _resolve_branch(self) -> str:
        addons = getattr(self.config, "addons", None)
        argocd = getattr(addons, "argocd", None) if addons else None
        repo = getattr(argocd, "repository", None) if argocd else None
        if repo and getattr(repo, "branch", None):
            return repo.branch
        return "main"

    def _get_output(self, key: str) -> str:
        value = self.outputs.get(key)
        if not value:
            raise ValueError(f"Required Pulumi output '{key}' not found")
        return value

    def _customer_host(self, subdomain: str) -> str:
        return f"{subdomain}.{self.domain}"

    def generate_customer_values(self) -> Dict[str, str]:
        region = self.config.aws_config.region
        org = self.customer_id

        irsa_role_arn = self._get_output("cortex_app_role_arn")
        documents_bucket = self._get_output("documents_bucket_name")
        local_sources_bucket = self._get_output("local_sources_bucket_name")
        cortex_users_table = self._get_output("cortex_users_table_name")
        api_keys_table = self._get_output("api_keys_table_name")
        tenant_mapping_table = self._get_output("tenant_mapping_table_name")
        user_metadata_table = self._get_output("user_metadata_table_name")
        user_indexed_data_table = self._get_output("user_indexed_data_table_name")
        user_details_table = self._get_output("user_details_table_name")
        users_to_sign_up_table = self._get_output("users_to_sign_up_table_name")
        token_bucket_table = self._get_output("token_bucket_table_name")

        cortex_app_values = f"""# Auto-generated by BYOC platform. Do not edit manually.
serviceAccount:
  irsaRoleArn: "{irsa_role_arn}"

config:
  AWS_REGION: "{region}"
  ORG: "{org}"
  FALKORDB_HOST: "falkordb-{org}-tenant-1-falkordb-falkordb.falkordb-{org}.svc.cluster.local"
  MILVUS_URI: "http://{org}-milvus.milvus-{org}.svc.cluster.local:19530"
  MINIO_ENDPOINT: "s3.{region}.amazonaws.com"
  MINIO_SECURE: "true"
  MINIO_BUCKET: "{documents_bucket}"
  KAFKA_BOOTSTRAP_SERVERS: ""
  NEXTAUTH_TABLE_NAME: "{cortex_users_table}"
  CORTEX_API_KEYS_TABLE_NAME: "{api_keys_table}"
  CORTEX_LOCAL_SOURCES_BUCKET_NAME: "{local_sources_bucket}"
  TENANT_ID_MAPPING_TABLE_NAME: "{tenant_mapping_table}"
  USER_METADATA_TABLE_NAME: "{user_metadata_table}"
  USER_INDEXED_DATA_TABLE: "{user_indexed_data_table}"
  USER_DETAILS_TABLE_NAME: "{user_details_table}"
  USERS_TO_SIGN_UP_TABLE_NAME: "{users_to_sign_up_table}"
  TOKEN_BUCKET_TABLE_NAME: "{token_bucket_table}"
  VECTOR_PUSH_URL: "https://vector.{self.domain}"

ingress:
  hostname: "cortex-app.{self.domain}"

externalSecrets:
  secretKey: "/byoc/{org}/cortex-app"
  argocdTokenSecretKey: "/byoc/{org}/argocd-generated-tokens"
"""

        cortex_ingestion_values = f"""# Auto-generated by BYOC platform. Do not edit manually.
serviceAccount:
  irsaRoleArn: "{irsa_role_arn}"

config:
  AWS_REGION: "{region}"
  ORG: "{org}"
  FALKORDB_HOST: "falkordb-{org}-tenant-1-falkordb-falkordb.falkordb-{org}.svc.cluster.local"
  MILVUS_URI: "http://{org}-milvus.milvus-{org}.svc.cluster.local:19530"
  MINIO_ENDPOINT: "s3.{region}.amazonaws.com"
  MINIO_SECURE: "true"
  MINIO_BUCKET: "{documents_bucket}"
  KAFKA_BOOTSTRAP_SERVERS: ""
  VECTOR_PUSH_URL: "https://vector.{self.domain}"
  CORTEX_API_KEYS_TABLE_NAME: "{api_keys_table}"
  USER_INDEXED_DATA_TABLE: "{user_indexed_data_table}"
  TOKEN_BUCKET_TABLE_NAME: "{token_bucket_table}"

ingress:
  hostname: "cortex-ingestion.{self.domain}"

externalSecrets:
  secretKey: "/byoc/{org}/cortex-ingestion"
"""

        from api.settings import settings as ps

        nextjs_config_lines = [
            f'  NEXT_PUBLIC_APP_URL: "https://nextjs.{self.domain}"',
            f'  NEXT_PUBLIC_CORTEX_API_URL: "https://cortex-app.{self.domain}"',
            f'  NEXT_PUBLIC_CORTEX_INGESTION_URL: "https://cortex-ingestion.{self.domain}"',
            f'  NEXT_PUBLIC_FALKORDB_DASHBOARD_URL: "https://dashboard.falkordb.{self.domain}"',
            f'  NEXT_PUBLIC_MILVUS_ATTU_URL: "https://{org}-attu.milvusdb.{self.domain}"',
            f'  NEXT_PUBLIC_GRAFANA_URL: "https://grafana-prod.{self.domain}"',
            f'  NEXT_PUBLIC_PROMETHEUS_URL: "https://prometheus-prod.{self.domain}"',
        ]

        if ps.nextjs_frontend_config:
            nextjs_config_lines.append(
                f"  NEXT_PUBLIC_FRONTEND_CONFIG: '{ps.nextjs_frontend_config}'"
            )
        if ps.nextjs_nextauth_url:
            nextjs_config_lines.append(f'  NEXTAUTH_URL: "{ps.nextjs_nextauth_url}"')
        if ps.nextjs_auth_dynamodb_region:
            nextjs_config_lines.append(
                f'  AUTH_DYNAMODB_REGION: "{ps.nextjs_auth_dynamodb_region}"'
            )
        nextjs_config_lines.append(f'  NEXTAUTH_TABLE_NAME: "{cortex_users_table}"')
        if ps.nextjs_email_from:
            nextjs_config_lines.append(f'  EMAIL_FROM: "{ps.nextjs_email_from}"')

        nextjs_config_block = "\n".join(nextjs_config_lines)

        nextjs_eso_block = f"""
externalSecret:
  enabled: true
  storeName: aws-secrets-manager
  secretPath: /byoc/{org}/nextjs"""

        nextjs_values = f"""# Auto-generated by BYOC platform. Do not edit manually.
config:
{nextjs_config_block}

ingress:
  hostname: "nextjs.{self.domain}"
{nextjs_eso_block}
"""

        monitoring_values = f"""# Auto-generated by BYOC platform. Do not edit manually.
grafana:
  host: "grafana-prod.{self.domain}"

prometheus:
  host: "prometheus-prod.{self.domain}"
"""

        falkordb_values = f"""# Auto-generated by BYOC platform. Do not edit manually.
organization: "{org}"

namespace: "falkordb-{org}"

ingress:
  domain: "falkordb.{self.domain}"
"""

        milvus_values = f"""# Auto-generated by BYOC platform. Do not edit manually.
org_id: "{org}"

milvus:
  config:
    maxVectorFieldNum: 10

ingress:
  domain: "milvusdb.{self.domain}"
"""

        falkordb_dashboard_values = f"""# Auto-generated by BYOC platform. Do not edit manually.
ingress:
  hostname: "dashboard.falkordb.{self.domain}"
"""

        base_path = f"gitops/{self.customer_id}/values"

        return {
            f"{base_path}/cortex-app-values.yaml": cortex_app_values,
            f"{base_path}/cortex-ingestion-values.yaml": cortex_ingestion_values,
            f"{base_path}/nextjs-values.yaml": nextjs_values,
            f"{base_path}/monitoring-values.yaml": monitoring_values,
            f"{base_path}/falkordb-values.yaml": falkordb_values,
            f"{base_path}/milvus-values.yaml": milvus_values,
            f"{base_path}/falkordb-dashboard-values.yaml": falkordb_dashboard_values,
        }

    def _application_header(self, name: str, wave: int) -> str:
        return f"""apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {name}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{wave}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
"""

    def generate_customer_apps(self) -> Dict[str, str]:
        addons = getattr(self.config, "addons", None)
        argocd = getattr(addons, "argocd", None) if addons else None
        repo_cfg = getattr(argocd, "repository", None) if argocd else None

        if repo_cfg and getattr(repo_cfg, "url", None):
            repo_url = repo_cfg.url
        else:
            repo_url = f"https://github.com/{settings.github_repo}.git"
        customer_path = f"gitops/{self.customer_id}/apps"
        values_ref = "values"

        cortex_app_app = (
            self._application_header("cortex-app", 4)
            + f"""  sources:
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      ref: {values_ref}
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      path: prod/cortex-app/helm/cortex-app-chart
      helm:
        releaseName: cortex-app
        valueFiles:
          - $values/gitops/{self.customer_id}/values/cortex-app-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cortex-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jqPathExpressions:
        - .metadata.annotations
        - .spec.rules
        - .spec.tls
"""
        )

        cortex_ingestion_app = (
            self._application_header("cortex-ingestion", 4)
            + f"""  sources:
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      ref: {values_ref}
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      path: prod/cortex-ingestion/helm/cortex-ingestion-chart
      helm:
        releaseName: cortex-ingestion
        valueFiles:
          - $values/gitops/{self.customer_id}/values/cortex-ingestion-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cortex-ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jqPathExpressions:
        - .metadata.annotations
        - .spec.rules
        - .spec.tls
"""
        )

        nextjs_app = (
            self._application_header("nextjs", 5)
            + f"""  sources:
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      ref: {values_ref}
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      path: prod/nextjs/helm/nextjs-chart
      helm:
        releaseName: nextjs
        valueFiles:
          - $values/gitops/{self.customer_id}/values/nextjs-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nextjs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jqPathExpressions:
        - .metadata.annotations
        - .spec.rules
        - .spec.tls
"""
        )

        monitoring_ingress_app = (
            self._application_header("monitoring-ingresses", 3)
            + f"""  sources:
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      ref: {values_ref}
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      path: prod/monitoring/helm/monitoring-ingresses
      helm:
        releaseName: monitoring-ingresses
        valueFiles:
          - $values/gitops/{self.customer_id}/values/monitoring-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /metadata/annotations
        - /metadata/finalizers
"""
        )

        falkordb_app = (
            self._application_header("falkordb", 2)
            + f"""  sources:
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      ref: {values_ref}
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      path: prod/falkordb/helm/falkor-chart
      helm:
        releaseName: falkordb
        valueFiles:
          - $values/gitops/{self.customer_id}/values/falkordb-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: falkordb-{self.customer_id}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps.kubeblocks.io
      kind: Cluster
      jqPathExpressions:
        - .spec
        - .metadata.annotations
        - .metadata.finalizers
"""
        )

        milvus_app = (
            self._application_header("milvus", 2)
            + f"""  sources:
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      ref: {values_ref}
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      path: prod/milvus/helm/milvus-chart
      helm:
        releaseName: milvus
        valueFiles:
          - $values/gitops/{self.customer_id}/values/milvus-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: milvus-{self.customer_id}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: milvus.io
      kind: Milvus
      jqPathExpressions:
        - .spec.components
        - .spec.dependencies
"""
        )

        falkordb_dashboard_app = (
            self._application_header("falkordb-dashboard", 3)
            + f"""  sources:
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      ref: {values_ref}
    - repoURL: {repo_url}
      targetRevision: {self.branch}
      path: prod/falkordb-dashboard/helm/falkordb-dashboard-chart
      helm:
        releaseName: falkordb-dashboard
        valueFiles:
          - $values/gitops/{self.customer_id}/values/falkordb-dashboard-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: falkordb-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jqPathExpressions:
        - .metadata.annotations
        - .spec.rules
        - .spec.tls
"""
        )

        clickhouse_app = (
            self._application_header("clickhouse", 2)
            + f"""  source:
    repoURL: {repo_url}
    targetRevision: {self.branch}
    path: prod/clickhouse/helm/clickhouse-chart
    helm:
      releaseName: clickhouse
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: clickhouse.altinity.com
      kind: ClickHouseInstallation
      managedFieldsManagers:
        - clickhouse-operator
    - group: clickhouse-keeper.altinity.com
      kind: ClickHouseKeeperInstallation
      managedFieldsManagers:
        - clickhouse-operator
"""
        )

        grafana_dashboards_app = (
            self._application_header("grafana-dashboards", 4)
            + f"""  source:
    repoURL: {repo_url}
    targetRevision: {self.branch}
    path: prod/monitoring/dashboards
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
"""
        )

        vector_app = (
            self._application_header("vector", 3)
            + f"""  source:
    repoURL: {repo_url}
    targetRevision: {self.branch}
    path: prod/vector_dev/helm/vector-chart
    helm:
      releaseName: vector
  destination:
    server: https://kubernetes.default.svc
    namespace: vector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
"""
        )

        nginx_app = """apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-inc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.nginx.com/stable
    chart: nginx-ingress
    targetRevision: "1.4.0"
    helm:
      releaseName: nginx-inc
      values: |
        controller:
          ingressClass:
            name: nginx-inc
            setAsDefaultIngress: true

          config:
            entries:
              http2: "true"

          enableTLSPassthrough: true

          globalConfiguration:
            create: false

          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"

          replicaCount: 2

          nodeSelector:
            role: general

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-inc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Service
      name: nginx-inc-nginx-ingress-controller
      jqPathExpressions:
        - .spec.ports[].nodePort
      jsonPointers:
        - /metadata/annotations
        - /metadata/finalizers
        - /spec/externalTrafficPolicy
        - /spec/allocateLoadBalancerNodePorts
        - /spec/healthCheckNodePort
        - /spec/clusterIP
        - /spec/clusterIPs
        - /spec/ipFamilies
        - /spec/ipFamilyPolicy
        - /status
"""

        return {
            f"{customer_path}/cortex-app.yaml": cortex_app_app,
            f"{customer_path}/cortex-ingestion.yaml": cortex_ingestion_app,
            f"{customer_path}/nextjs.yaml": nextjs_app,
            f"{customer_path}/monitoring-ingress.yaml": monitoring_ingress_app,
            f"{customer_path}/falkordb.yaml": falkordb_app,
            f"{customer_path}/milvus.yaml": milvus_app,
            f"{customer_path}/falkordb-dashboard.yaml": falkordb_dashboard_app,
            f"{customer_path}/clickhouse.yaml": clickhouse_app,
            f"{customer_path}/grafana-dashboards.yaml": grafana_dashboards_app,
            f"{customer_path}/vector.yaml": vector_app,
            f"{customer_path}/nginx.yaml": nginx_app,
        }

    def push_to_github(self) -> None:
        values_files = self.generate_customer_values()
        app_files = self.generate_customer_apps()
        all_files = {**values_files, **app_files}

        if not all_files:
            return

        token = settings.github_pat
        repo = settings.github_repo

        if not token or not repo:
            raise ValueError("GitHub PAT and repository must be configured in settings")

        owner, name = repo.split("/", 1)
        base_url = "https://api.github.com"
        headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github+json",
        }

        ref_resp = requests.get(
            f"{base_url}/repos/{owner}/{name}/git/ref/heads/{self.branch}",
            headers=headers,
            timeout=10,
        )
        ref_resp.raise_for_status()
        ref_data = ref_resp.json()
        latest_commit_sha = ref_data["object"]["sha"]

        commit_resp = requests.get(
            f"{base_url}/repos/{owner}/{name}/git/commits/{latest_commit_sha}",
            headers=headers,
            timeout=10,
        )
        commit_resp.raise_for_status()
        commit_data = commit_resp.json()
        base_tree_sha = commit_data["tree"]["sha"]

        blobs: Dict[str, str] = {}
        for path, content in all_files.items():
            blob_resp = requests.post(
                f"{base_url}/repos/{owner}/{name}/git/blobs",
                headers=headers,
                json={
                    "content": content,
                    "encoding": "utf-8",
                },
                timeout=10,
            )
            blob_resp.raise_for_status()
            blobs[path] = blob_resp.json()["sha"]

        tree_entries = [
            {
                "path": path,
                "mode": "100644",
                "type": "blob",
                "sha": sha,
            }
            for path, sha in blobs.items()
        ]

        tree_resp = requests.post(
            f"{base_url}/repos/{owner}/{name}/git/trees",
            headers=headers,
            json={
                "base_tree": base_tree_sha,
                "tree": tree_entries,
            },
            timeout=10,
        )
        tree_resp.raise_for_status()
        new_tree_sha = tree_resp.json()["sha"]

        commit_message = f"chore: generate GitOps values for {self.customer_id}"
        new_commit_resp = requests.post(
            f"{base_url}/repos/{owner}/{name}/git/commits",
            headers=headers,
            json={
                "message": commit_message,
                "tree": new_tree_sha,
                "parents": [latest_commit_sha],
            },
            timeout=10,
        )
        new_commit_resp.raise_for_status()
        new_commit_sha = new_commit_resp.json()["sha"]

        update_ref_resp = requests.patch(
            f"{base_url}/repos/{owner}/{name}/git/refs/heads/{self.branch}",
            headers=headers,
            json={"sha": new_commit_sha, "force": False},
            timeout=10,
        )
        update_ref_resp.raise_for_status()

