apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-milvus
  namespace: argocd
spec:
  description: "Milvus clusters for all orgs"
  
  sourceRepos:
    - https://github.com/opengig/cortex.git
  
  destinations:
    - namespace: 'milvus-*'
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'storage.k8s.io'
      kind: StorageClass
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  
  orphanedResources:
    warn: true