apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cortex-app-external-secrets
  namespace: cortex-app
  labels:
    app.kubernetes.io/name: cortex-app
    app.kubernetes.io/component: external-secrets
spec:
  # Refresh interval - how often to sync from AWS
  # 5 minutes for fast propagation of secret changes
  refreshInterval: 5m
  
  # Reference to the ClusterSecretStore
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  
  # Target Kubernetes secret configuration
  target:
    name: cortex-app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: cortex-app
          app.kubernetes.io/component: secrets
          app.kubernetes.io/managed-by: external-secrets
  
  # Data mappings from AWS Secrets Manager
  data:
    # Database credentials
    - secretKey: FALKORDB_PASSWORD
      remoteRef:
        key: cortex/prod/app-secrets
        property: FALKORDB_PASSWORD
    
    - secretKey: FALKORDB_USER
      remoteRef:
        key: cortex/prod/app-secrets
        property: FALKORDB_USER
    
    - secretKey: MONGODB_CLUSTER_CONNECTION_URI
      remoteRef:
        key: cortex/prod/app-secrets
        property: MONGODB_CLUSTER_CONNECTION_URI
    
    # LLM API Keys
    - secretKey: COHERE_API_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: COHERE_API_KEY
    
    - secretKey: VOYAGE_API_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: VOYAGE_API_KEY
    
    - secretKey: GROQ_API_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: GROQ_API_KEY
    
    - secretKey: CEREBRAS_API_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: CEREBRAS_API_KEY
    
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: OPENAI_API_KEY
    
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: ANTHROPIC_API_KEY
    
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: GOOGLE_API_KEY
    
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: GEMINI_API_KEY
    
    # Infrastructure secrets
    - secretKey: GITHUB_ARGOCD_CD_TOKEN
      remoteRef:
        key: cortex/prod/app-secrets
        property: GITHUB_ARGOCD_CD_TOKEN
    
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: cortex/prod/app-secrets
        property: NEXTAUTH_SECRET
    
    - secretKey: CORTEX_INTERNAL_SECRET
      remoteRef:
        key: cortex/prod/app-secrets
        property: CORTEX_INTERNAL_SECRET
    
    - secretKey: ARGO_CD_API_TOKEN
      remoteRef:
        key: cortex/prod/app-secrets
        property: ARGO_CD_API_TOKEN
    
    - secretKey: MILVUS_TOKEN
      remoteRef:
        key: cortex/prod/app-secrets
        property: MILVUS_TOKEN
    
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: MINIO_ACCESS_KEY
    
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: MINIO_SECRET_KEY
    
    # Firebase credentials
    - secretKey: FIREBASE_TYPE
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_TYPE
    
    - secretKey: FIREBASE_PROJECT_ID
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_PROJECT_ID
    
    - secretKey: FIREBASE_PRIVATE_KEY_ID
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_PRIVATE_KEY_ID
    
    - secretKey: FIREBASE_PRIVATE_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_PRIVATE_KEY
    
    - secretKey: FIREBASE_CLIENT_EMAIL
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_CLIENT_EMAIL
    
    - secretKey: FIREBASE_CLIENT_ID
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_CLIENT_ID
    
    - secretKey: FIREBASE_AUTH_URI
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_AUTH_URI
    
    - secretKey: FIREBASE_TOKEN_URI
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_TOKEN_URI
    
    - secretKey: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
    
    - secretKey: FIREBASE_CLIENT_X509_CERT_URL
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_CLIENT_X509_CERT_URL
    
    - secretKey: FIREBASE_UNIVERSE_DOMAIN
      remoteRef:
        key: cortex/prod/app-secrets
        property: FIREBASE_UNIVERSE_DOMAIN
    
    # JWT
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: cortex/prod/app-secrets
        property: JWT_SECRET_KEY
