apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cortex-ingestion-external-secrets
  namespace: cortex-ingestion
  labels:
    app.kubernetes.io/name: cortex-ingestion
    app.kubernetes.io/component: external-secrets
spec:
  # Refresh interval - how often to sync from AWS
  # 5 minutes for fast propagation of secret changes
  refreshInterval: 5m
  
  # Reference to the ClusterSecretStore
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  
  # Target Kubernetes secret configuration
  target:
    name: cortex-ingestion-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: cortex-ingestion
          app.kubernetes.io/component: secrets
          app.kubernetes.io/managed-by: external-secrets
  
  # Data mappings from AWS Secrets Manager
  data:
    # Database credentials
    - secretKey: MONGODB_CLUSTER_CONNECTION_URI
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: MONGODB_CLUSTER_CONNECTION_URI
    
    - secretKey: FALKORDB_PASSWORD
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: FALKORDB_PASSWORD
    
    - secretKey: FALKORDB_USER
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: FALKORDB_USER
    
    # LLM API Keys
    - secretKey: CEREBRAS_API_KEY
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: CEREBRAS_API_KEY
    
    - secretKey: GROQ_API_KEY
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: GROQ_API_KEY
    
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: OPENAI_API_KEY
    
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: ANTHROPIC_API_KEY
    
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: GEMINI_API_KEY
    
    # Infrastructure secrets
    - secretKey: MILVUS_TOKEN
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: MILVUS_TOKEN
    
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: MINIO_ACCESS_KEY
    
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: MINIO_SECRET_KEY
    
    - secretKey: SLACK_LOGGING_URL
      remoteRef:
        key: cortex/prod/ingestion-secrets
        property: SLACK_LOGGING_URL
