apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/opengig/cortex.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/opengig/cortex.git
      targetRevision: main
      path: prod/milvus/helm/milvus-chart
      helm:
        releaseName: milvus
        valueFiles:
          - $values/gitops/heizen/values/milvus-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: milvus-heizen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: milvus.io
      kind: Milvus
      jqPathExpressions:
        - .spec.components
        - .spec.dependencies
