apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cortex-app-pdb
  namespace: cortex-app
  labels:
    app.kubernetes.io/name: cortex-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cortex-app

