# Wildcard Certificate for *.milvusdb.usecortex.ai
# This creates a single wildcard cert that covers all tenant subdomains
# Apply once, then reference the secret in ingresses
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milvus-wildcard-cert
  namespace: milvus-cortexai
spec:
  secretName: milvus-wildcard-tls
  issuerRef:
    name: letsencrypt-dns01-milvus
    kind: ClusterIssuer
  commonName: "*.milvusdb.usecortex.ai"
  dnsNames:
    - "*.milvusdb.usecortex.ai"
    - "milvusdb.usecortex.ai"
  duration: 2160h    # 90 days
  renewBefore: 360h  # 15 days before expiry
