apiVersion: v1
kind: Service
metadata:
  name: cortex-ingestion
  namespace: cortex-ingestion
  labels:
    app.kubernetes.io/name: cortex-ingestion
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cortex-ingestion
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cortex-ingestion
  namespace: cortex-ingestion
  labels:
    app.kubernetes.io/name: cortex-ingestion
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746038690600:role/cortex-ingestion-sa-role

