apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cortex-ingestion-monitor
  namespace: cortex-ingestion
  labels:
    app.kubernetes.io/name: cortex-ingestion
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cortex-ingestion
  namespaceSelector:
    matchNames:
      - cortex-ingestion
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

