apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: falkordb-prod
  namespace: falkordb
spec:
  terminationPolicy: Delete
  clusterDef: falkordb
  topology: replication

  componentSpecs:
  # --- DATA NODES ---
  - name: falkordb
    serviceVersion: "4.12.5"
    replicas: 2
    disableExporter: false
    resources:
      requests:
        cpu: "500m"    # 0.5 vCPU (Guaranteed)
        memory: "4Gi"  # 4 GB (Guaranteed)
      limits:
        cpu: "1500m"   # 1.5 vCPU (Leaves room for OS)
        memory: "12Gi" # 12 GB (Leaves room for OS)
    
    schedulingPolicy:
      nodeSelector:
        role: memory-db
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "database"
        effect: "NoSchedule"
      
    volumeClaimTemplates:
    - name: data
      spec:
        storageClassName: falkordb-prod-gp3
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi

  # --- SENTINEL NODES ---
  - name: falkordb-sent
    replicas: 3
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    
    schedulingPolicy:
      nodeSelector:
        role: general
      
    volumeClaimTemplates:
    - name: data
      spec:
        storageClassName: falkordb-general-gp3
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi