apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: falkordb-prod-monitor
  namespace: falkordb
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: falkordb-exporter
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s