apiVersion: v1
kind: ConfigMap
metadata:
  name: falkordb-stats-exporter-script
  namespace: falkordb
data:
  exporter.py: |
    #!/usr/bin/env python3
    import os
    import time
    import redis
    from prometheus_client import start_http_server, Gauge, Counter

    # Metrics
    graph_nodes = Gauge('falkordb_graph_nodes_total', 'Total nodes in graph', ['graph'])
    graph_edges = Gauge('falkordb_graph_edges_total', 'Total edges in graph', ['graph'])
    graph_count = Gauge('falkordb_graphs_total', 'Total number of graphs')
    scrape_errors = Counter('falkordb_scrape_errors_total', 'Total scrape errors', ['graph'])

    def get_redis_client():
        return redis.Redis(
            host=os.environ.get('REDIS_HOST', 'localhost'),
            port=int(os.environ.get('REDIS_PORT', 6379)),
            password=os.environ.get('REDIS_PASSWORD', ''),
            decode_responses=True
        )

    def collect_metrics():
        try:
            r = get_redis_client()
            
            # Get list of all graphs
            graphs = r.execute_command('GRAPH.LIST')
            graph_count.set(len(graphs))
            
            for graph_name in graphs:
                try:
                    # Get node count
                    result = r.execute_command('GRAPH.QUERY', graph_name, 'MATCH (n) RETURN count(n)')
                    # Result format: [headers, [[count]], stats]
                    nodes = result[1][0][0]
                    graph_nodes.labels(graph=graph_name).set(nodes)
                    
                    # Get edge count
                    result = r.execute_command('GRAPH.QUERY', graph_name, 'MATCH ()-[r]->() RETURN count(r)')
                    edges = result[1][0][0]
                    graph_edges.labels(graph=graph_name).set(edges)
                    
                except Exception as e:
                    print(f"Error collecting metrics for graph {graph_name}: {e}")
                    scrape_errors.labels(graph=graph_name).inc()
                    
        except Exception as e:
            print(f"Error connecting to Redis: {e}")

    if __name__ == '__main__':
        port = int(os.environ.get('EXPORTER_PORT', 9122))
        interval = int(os.environ.get('SCRAPE_INTERVAL', 60))
        
        print(f"Starting FalkorDB stats exporter on port {port}")
        start_http_server(port)
        
        while True:
            collect_metrics()
            time.sleep(interval)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: falkordb-stats-exporter
  namespace: falkordb
  labels:
    app: falkordb-stats-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falkordb-stats-exporter
  template:
    metadata:
      labels:
        app: falkordb-stats-exporter
    spec:
      containers:
      - name: exporter
        image: python:3.11-slim
        command:
        - /bin/bash
        - -c
        - |
          pip install --quiet redis prometheus_client && \
          python /scripts/exporter.py
        env:
        - name: REDIS_HOST
          value: "falkordb-prod-falkordb-falkordb.falkordb.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: falkordb-prod-falkordb-account-default
              key: password
        - name: EXPORTER_PORT
          value: "9122"
        - name: SCRAPE_INTERVAL
          value: "60"
        ports:
        - name: http-metrics
          containerPort: 9122
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: script
          mountPath: /scripts
        livenessProbe:
          httpGet:
            path: /
            port: http-metrics
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http-metrics
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: script
        configMap:
          name: falkordb-stats-exporter-script
      nodeSelector:
        role: general
---
apiVersion: v1
kind: Service
metadata:
  name: falkordb-stats-exporter
  namespace: falkordb
  labels:
    app: falkordb-stats-exporter
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 9122
    targetPort: http-metrics
    protocol: TCP
  selector:
    app: falkordb-stats-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: falkordb-stats-monitor
  namespace: falkordb
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: falkordb-stats-exporter
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 60s
