apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: falkordb-prod-gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "4000"       
  throughput: "250"   
  fsType: ext4
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain 