apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:api-read-only, applications, get, */*, allow
    g, api_user, role:api-read-only
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'