apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: cluster01
spec:
  templates:
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          tolerations:
            - key: workload
              value: clickhouse
              effect: NoSchedule
          nodeSelector:
            role: clickhouse
          containers:
            - name: clickhouse
              image: altinity/clickhouse-server:25.3.6.10034.altinitystable
              ports:
                - name: metrics
                  containerPort: 9363
                  protocol: TCP
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: clickhouse-storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: clickhouse-storage
  configuration:
    settings:
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      prometheus/metrics: true
      prometheus/events: true
      prometheus/asynchronous_metrics: true
      
      # Disable or set TTL on ALL system log tables to prevent disk bloat
      # Trace log - disabled
      trace_log/enabled: false
      
      # Metric log - main culprit, disable completely
      metric_log/enabled: false
      
      # Asynchronous metric log - disable
      asynchronous_metric_log/enabled: false
      
      # Query log - keep but with short TTL (3 days)
      query_log/partition_by: toYYYYMM(event_date)
      query_log/ttl: "event_date + INTERVAL 3 DAY"
      
      # Query thread log - disable (very verbose)
      query_thread_log/enabled: false
      
      # Part log - keep with short TTL
      part_log/partition_by: toYYYYMM(event_date)
      part_log/ttl: "event_date + INTERVAL 3 DAY"
      
      # Text log - disable
      text_log/enabled: false
      
      # Session log - disable
      session_log/enabled: false
      # Increase memory limits for large queries
      max_memory_usage: 8000000000
      max_memory_usage_for_user: 8000000000
      max_memory_usage_for_all_queries: 16000000000
      memory_overcommit_ratio_denominator: 2
    users:
      # Default user - secured with password
      default/password_sha256_hex: "73bb8a3438b824e24f3a5cab7bf0f48ddd3cff6ede677ca0087b824a8e29a36a"
      default/networks/ip: "::/0"
      # Admin user
      admin/password_sha256_hex: "4c6d7299d9505f1aef715179d27e5ec2af1c92b26f76e78598fc7dd397dbf2b0"
      admin/networks/ip: "::/0"
      admin/profile: default
      admin/quota: default
    zookeeper:
      nodes:
        - host: keeper-clickhouse-keeper.clickhouse.svc.cluster.local
          port: 2181
    clusters:
      - name: cluster01
        secret:
          auto: "true"
        layout:
          shardsCount: 1
          replicasCount: 2
        templates:
          podTemplate: clickhouse-pod-template
