apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: clickhouse-server-metrics
  namespace: clickhouse
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      clickhouse.altinity.com/chi: cluster01
  namespaceSelector:
    matchNames:
      - clickhouse
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
